vich_uploader:
    db_driver: orm
    
    mappings:
        listing_images:
            uri_prefix: /uploads/listings
            upload_destination: '%kernel.project_dir%/public/uploads/listings'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
        user_avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer